version: '2'

services:

  # elastic:
  #   image: docker.elastic.co/elasticsearch/elasticsearch:8.10.4
  #   environment:
  #     - discovery.type=single-node
  #     - xpack.security.enabled=false
  #   volumes:
  #     - sd-alpha-browser-index:/usr/share/elasticsearch/data
  #   ports:
  #     - 9220:9200
  #     - 9330:9300
  #   networks:
  #     - traefik-public

  # kibana:
  #     image: docker.elastic.co/kibana/kibana:8.10.4
  #     environment:
  #       ELASTICSEARCH_URL: http://elastic:9200
  #       ELASTICSEARCH_HOSTS: '["http://elastic:9200"]'    
  #     ports:
  #       - 5601:5601 
  #     networks:
  #       - index_network


  yugo-browser:
    build:
      context: ./browser
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.sd-alpha-browser.loadbalancer.server.port=5000"
      - "traefik.http.routers.sd-alpha-browser.entrypoints=http"
      - "traefik.http.routers.sd-alpha-browser.rule=Host(`alpha-browser.sd.di.huc.knaw.nl`)"
    ports:
      - '5050:5000'

  yugo-indexer:
    build:
      context: ./indexer
    volumes:
      - sd-alpha-browser-apps:/data/apps
    networks:
      - traefik-public

volumes:
  sd-alpha-browser-index:
  sd-alpha-browser-apps:
    external: true

networks:
  traefik-public:
    external: true
