version: '2'

networks:
  index_network:
    external: false

volumes:
  index_es:

services:

  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.10.4
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    volumes:
      - ./index:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - index_network

  kibana:
      image: docker.elastic.co/kibana/kibana:8.10.4
      environment:
        ELASTICSEARCH_URL: http://elastic:9200
        ELASTICSEARCH_HOSTS: '["http://elastic:9200"]'    
      ports:
        - 5601:5601 
      networks:
        - index_network


  yugo-browser:
    image: yugo-browser:latest
    ports:
      - '5050:5000'