[index]
host="http://elastic:9200/"
name="niod-yugo-collection"
full_text="yes"

[index.input]
format="xml"

[index.input.ns]
cmd="http://www.clarin.eu/cmd/1"
cmdp="http://www.clarin.eu/cmd/1/profiles/clarin.eu:cr1:p_1747312582429"

[index.id]
path="string(replace(/cmd:CMD/cmd:Header/cmd:MdSelfLink,'unl://',''))"

[index.facet.collection_id]
path="string(replace(/cmd:CMD/cmd:Header/cmd:MdSelfLink,'unl://',''))"
type="number"
cardinality="single"

[index.facet.type]
path="string(/cmd:CMD/cmd:Components/cmdp:Collection/cmdp:Identification/cmdp:type)"
type="text"
cardinality="single"

[index.facet.name]
path="/cmd:CMD/cmd:Components/cmdp:Collection/cmdp:Identification/cmdp:Names/(cmdp:authorisedForm,cmdp:parallelForms,cmdp:otherForms)/string()"
type="text"
cardinality="list"

[index.facet.authorisedForm]
path="string(/cmd:CMD/cmd:Components/cmdp:Collection/cmdp:Identification/cmdp:Names/(cmdp:authorisedForm[@xml:lang='en'],cmdp:authorisedForm)[1])"
type="text"
cardinality="single"

[index.facet.level]
path="string(/cmd:CMD/cmd:Components/cmdp:Collection/cmdp:CollectionSpecificIdentityArea/cmdp:levelOfDescription)"
type="text"
cardinality="single"

[index.facet.scope]
path="string(/cmd:CMD/cmd:Components/cmdp:Collection/cmdp:ContentAndStructureArea/(cmdp:scopeAndContent[@xml:lang='en'],cmdp:scopeAndContent)[1])"
type="text"
cardinality="single"

[index.facet.institution]
path="doc('https://alpha-editor.sd.di.huc.knaw.nl/app/yugo/action/graph')//collectionHierarchy//collection[@id=$id]/ancestor::institution/@title/string()"
type="text"
cardinality="single"
