
[index]
host="https://195.169.89.231:9200/"
name="niod-yugo-group"
full_text="yes"

[index.input]
format="xml"

[index.input.ns]
cmd="http://www.clarin.eu/cmd/1"
cmdp="http://www.clarin.eu/cmd/1/profiles/clarin.eu:cr1:p_1747312582450"

[index.id]
path="string(replace(/cmd:CMD/cmd:Header/cmd:MdSelfLink,'unl://',''))"

[index.facet.group_id]
path="string(replace(/cmd:CMD/cmd:Header/cmd:MdSelfLink,'unl://',''))"
type="number"
cardinality="single"

[index.facet.type]
path="/cmd:CMD/cmd:Components/cmdp:Group/cmdp:Identification/cmdp:type/string()"
type="text"
cardinality="single"

[index.facet.name]
path="/cmd:CMD/cmd:Components/cmdp:Group/cmdp:Identification/cmdp:Names/(cmdp:authorisedForm,cmdp:parallelForms)/string()"
type="text"
cardinality="list"

[index.facet.authorisedForm]
path="string(/cmd:CMD/cmd:Components/cmdp:Group/cmdp:Identification/cmdp:Names/(cmdp:authorisedForm[@xml:lang='en'],cmdp:authorisedForm)[1])"
type="text"
cardinality="single"

[index.facet.history]
path="string(/cmd:CMD/cmd:Components/cmdp:Group/cmdp:ActorDescriptionArea/(cmdp:history[@xml:lang='en'],cmdp:history)[1])"
type="type"
cardinality="single"
